export MLFLOW_EXPERIMENT_NAME="YOOUR_MLFLOW_EXPERIMENT_NAME";
export MLFLOW_TRACKING_URI="YOUR_MLFLOW_TRACKING_URI";
export AWS_ACCESS_KEY_ID="YOUR_AWS_ACCESS_KEY_ID";
export AWS_SECRET_ACCESS_KEY="YOUR_AWS_SECRET_ACCESS_KEY";
export BACKEND_STORE_URI="YOUR_BACKEND_STORE_URI";
export ARTIFACT_ROOT=YOUR_ARTIFACT_ROOT