docker run -it \
 -v "$(pwd):/home/app" \
 -e MLFLOW_TRACKING_URI=YOUR_MLFLOW_TRACKING_URI \
 -e AWS_ACCESS_KEY_ID=YOUR_AWS_ACCESS_KEY_ID \
 -e AWS_SECRET_ACCESS_KEY=YOUR_AWS_SECRET_ACCESS_KEY \
 -e BACKEND_STORE_URI=YOUR_BACKEND_STORE_URI \
 -e ARTIFACT_ROOT=YOUR_ARTIFACT_ROOT \
 mlf-getaround python app.py